# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Set Dist Version
      run: |
        BUILD_NUMBER="${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}"
        echo "${BUILD_NUMBER}"
        VERSION="$(mvn -q -U -Dexpression=project.build.finalName help:evaluate -DforceStdout=true -DbuildNumber=${BUILD_NUMBER})"
        echo "DIST_VERSION=${VERSION}" >> $GITHUB_ENV
    - name: Create Tag
      uses: actions/github-script@v6
      with:
        script: |
          const {DIST_VERSION} = process.env          
          github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${DIST_VERSION}`,
              sha: context.sha
          })

    - name: GoReleaser Action
      uses: goreleaser/goreleaser-action@v5.0.0
      with:
          version: latest
          args: release --clean
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
